# Generated by Django 6.0.6 on 2026-08-04 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_restaurant_remove_booking_user_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('peoples', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(default='Простаивает', max_length=16)),
                ('booking_time', models.TextField(default='2026-08-04 20:39')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveSmallIntegerField()),
                ('text', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.booking')),
            ],
        ),
    ]
