# Generated by Django 6.0.6 on 2026-08-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_booking_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='89991234567', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TextField(default='2026-08-05 15:59'),
        ),
    ]
