# Generated by Django 6.0.6 on 2026-08-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_booking_booking_time_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TextField(default='2026-08-05 17:12'),
        ),
    ]
