# Generated by Django 6.0.6 on 2026-08-05 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_booking_booking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='booking',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
