# Generated by Django 6.0.6 on 2026-08-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_feedback_booking_delete_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
