# Generated by Django 6.0.6 on 2026-07-21 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 21, 23, 0, 30, 309128)),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Простаивает', max_length=16),
        ),
    ]
