# Generated by Django 6.0.6 on 2026-08-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TextField(default='2026-08-05 17:39'),
        ),
    ]
