# Generated by Django 6.1.1 on 2026-09-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_booking_time_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TextField(default='2026-09-08 19:52'),
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
