# Generated by Django 6.0.6 on 2026-09-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_remove_booking_status_alter_booking_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pre_order',
            field=models.TextField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TextField(default='2026-09-09 20:57'),
        ),
    ]
