# Generated by Django 6.0.6 on 2026-09-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_pre_order_alter_booking_booking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='booking',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TextField(default='2026-09-11 21:09'),
        ),
    ]
